<a href="https://colab.research.google.com/github/bud-code/JAX/blob/main/JAX_prac_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import jax.numpy as jnp

x = jnp.array([1, 2, 3])
y = x ** 2

print(y)

[1 4 9]


In [2]:
x = jnp.array([1, 2, 3, 4])

print(x)
print(x.shape)
print(x.dtype)

[1 2 3 4]
(4,)
int32


In [3]:
x = jnp.array([1, 2, 3])

print(x + 10)
print(x * 2)
print(x ** 2)
print(jnp.sum(x))
print(jnp.mean(x))

[11 12 13]
[2 4 6]
[1 4 9]
6
2.0


In [4]:
import jax

def f(x):
    return x ** 2

df = jax.grad(f)

print(df(5.0))

10.0
